### ISSUE TITLE
COPD Module uitbouwen

### ISSUE THREAD

**Issue by mvdzel** [dHealthNL/synthea-modules#7]

**Comment by Grettnn** [comment]
#2

**Comment by mvdzel** [comment]
1. Of iemand roker is of niet is nu willekeurig. Moeten we hier nog ¨echte¨ getallen voor hebben?
2. Hoe belangrijk is de duur bij een FEV Test? Heb nu op 30 minuten gezet.
3. Bij de ziektelastmeter hoort eigenlijk nog een Questionnaire in het dossier, maar in ons geval is de eind score genoeg denk ik. Weet alleen niet welke LOINC/SCT ik hieraan moet hangen.
4. Is het nog nodig om ¨Klachtenmanagement¨ verder uit te werken?
5. ¨Check Medicatie¨ heb ik even geinterpreteerd als voorschrijven.
6. Nu nog uitproberen of synthea runt met dit script...

**Comment by mvdzel** [comment]
Puntje 6 is gedaan. Data lijkt behoorlijk goed.
@Grettnn Stage van diagnose kan willekeurig wijzigen, maar is dat logisch?
